name: CI/CD

on:
  push:
    # Publish latest or develop branch as prerelease.
    branches: [ master, develop ]
    # Publish semver tags as releases.
    tags: [ '*.*.*' ]
    # and only if one of these files changed.
    paths:
      - .github/workflows/ci-cd.yml
      - .dockerignore
      - api.Dockerfile
      - pwa.Dockerfile

      # Below should match .dockerignore
      - '.docker/rootfs/**'

      - 'api/.docker/rootfs/**'
      - 'api/bin/**'
      - 'api/config/**'
      - 'api/migrations/**'
      - 'api/public/**'
      - 'api/src/**'
      - 'api/templates/**'
      - 'api/tests/**'
      - 'api/translations/**'
      - api/.env
      - api/.env.test
      - api/composer.json
      - api/composer.lock
      - api/phpunit.xml.dist
      - api/symfony.lock

      - 'pwa/.docker/rootfs/**'
      - 'pwa/src/**'
      - 'pwa/static/**'
      - 'pwa/tests/**'
      - pwa/.browserslistrc
      - pwa/.npmrc
      - pwa/package.json
      - pwa/playwright.config.ts
      - pwa/pnpm-lock.yaml
      - pwa/svelte.config.js
      - pwa/tsconfig.json
      - pwa/vite.config.ts
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@6e04d228eb30da1757ee4e1dd75a0ec73a653e06 #v3.1.1
        with:
          cosign-release: 'v2.1.1'

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          # Username and password (or personal access token if using 2FA) for Docker Hub login
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata (API)
        id: meta-api
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ vars.IMAGE_NAME }}
          flavor: |
            prefix=api-,onlatest=true
      - name: Extract Docker metadata (PWA)
        id: meta-pwa
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ vars.IMAGE_NAME }}
          flavor: |
            prefix=pwa-,onlatest=true

      - name: Start SSH agent for Docker build with '--mount=type=ssh'
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image (API)
        id: build-and-push-api
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          file: ./api.Dockerfile
          target: prod
          platforms: linux/amd64,linux/arm64
          ssh: |
            default
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push Docker image (PWA)
        id: build-and-push-pwa
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          file: ./pwa.Dockerfile
          target: prod
          platforms: linux/amd64,linux/arm64
          ssh: |
            default
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-pwa.outputs.tags }}
          labels: ${{ steps.meta-pwa.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data. If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image (API)
        if: ${{ github.event_name != 'pull_request' }}
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.meta-api.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-api.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
      - name: Sign the published Docker image (PWA)
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta-pwa.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-pwa.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
